@echo off
echo Başlatılıyor...
for %%p in (
    acres
    altgraph
    auto-py-to-exe
    blis
    bottle-websocket
    bs4
    catalogue
    chromedriver-py
    ci-info
    cloudpathlib
    cloudpickle
    confection
    configparser
    cymem
    dm-tree
    docstring_parser
    dp-accounting
    Eel
    et_xmlfile
    etelemetry
    etils
    fitz
    frontend
    gevent
    gevent-websocket
    httplib2
    immutabledict
    langcodes
    language_data
    looseversion
    marisa-trie
    murmurhash
    mypy-extensions
    nibabel
    nipype
    openpyxl
    pandas
    pefile
    preshed
    promise
    prov
    puremagic
    pydot
    pyinstaller
    pyinstaller-hooks-contrib
    PyMuPDF
    pyotp
    pypng
    pywin32-ctypes
    pyxnat
    pyzmq
    qrcode
    ratelim
    rdflib
    referencing
    responses
    retina-face
    retrying
    rfc3339-validator
    rfc3986-validator
    rpds-py
    ruff
    s3transfer
    safehttpx
    safetensors
    schedule
    selenium
    shellingham
    simple-parsing
    simple-websocket
    simsimd
    slicer
    smmap
    sortedcontainers
    spacy-legacy
    spacy-loggers
    sqlparse
    srsly
    stringzilla
    supervision
    tenacity
    tensorboard-data-server
    tensorflow-estimator
    tensorflow-io-gcs-filesystem
    tensorflow-metadata
    tensorflow-probability
    tensorflow_intel
    terminaltables
    text-unidecode
    thinc
    threadpoolctl
    tifffile
    timm
    tinycss2
    tokenizers
    toml
    tomli
    tomlkit
    tornado
    traits
    trio
    trio-websocket
    typer
    types-python-dateutil
    uri-template
    uvicorn
    wasabi
    wcwidth
    weasel
    webdriver-manager
    webencodings
    websocket-client
    whl
    widgetsnbextension
    wikipedia
    wsproto
    xxhash
    xyzservices
    yapf
    zipp
    zope.event
    zope.interface
) do (
    pip uninstall %%p -y
)
echo Tüm işlemler tamamlandı!
pause
